# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: cd frontend 
    - run: npm i
    - run: npm install react react-dom --save
    - run: npm install redux react-redux
    - run: npm install --save react-toastify
    - run: npm install react-router-dom --save
    - run: npm install react-icons --save
    - run: npm install react-scripts --save
    - run: npm install stream --save
    - run: npm install webpack --save
    - run: npm install react-app-polyfill --save
    - run: npm install crypto-js --save
    - run: npm install crypto --save
    - run: npm install core-js --save
    - run: npm install axios --save
    - run: npm install --save-dev react-app-rewired
    - run: npm install --save-dev crypto-browserify stream-browserify assert stream-http https-browserify os-browserify url buffer process
    - run: npm ci
    - run: npm run build --prefix frontend
    - run: npm test
